import type { UserCard } from "./types"

export const mockUserCards: UserCard[] = [
  {
    id: "EB01-006",
    name: "Tony Tony.Chopper",
    rarity: "SR",
    type: "CHARACTER",
    attribute: "Strike",
    power: 4000,
    counter: 1000,
    color: "Red",
    card_type: "Animal/Straw Hat Crew",
    effect:
      "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)[DON!! x2] [When Attacking] Give up to 1 of your opponent's Characters −3000 power during this turn.",
    image_url: "https://en.onepiece-cardgame.com/images/cardlist/card/EB01-006_r1.png",
    alternate_art: false,
    series_id: "569301",
    series_name: "ONE PIECE CARD THE BEST- [PRB-01]",
    market_price: 25.99,
    sellingPrice: 28.0,
    quantity: 2,
  },
  {
    id: "OP01-025",
    name: "Roronoa Zoro",
    rarity: "SR",
    type: "CHARACTER",
    attribute: "Slash",
    power: 5000,
    counter: 1000,
    color: "Green",
    card_type: "Swordsman/Straw Hat Crew",
    effect: "[DON!! x1] [When Attacking] K.O. up to 1 of your opponent's Characters with 3000 power or less.",
    image_url: "/placeholder.svg?height=838&width=600",
    alternate_art: false,
    series_id: "569302",
    series_name: "BOOSTER PACK ROMANCE DAWN [OP-01]",
    market_price: 45.99,
    sellingPrice: 50.0,
    quantity: 1,
  },
  {
    id: "OP01-039",
    name: "Nami",
    rarity: "R",
    type: "CHARACTER",
    attribute: "Special",
    power: 1000,
    counter: 1000,
    color: "Blue",
    card_type: "Navigator/Straw Hat Crew",
    effect:
      "[On Play] Look at 5 cards from the top of your deck; reveal up to 1 {Straw Hat Crew} type card other than [Nami] and add it to your hand. Then, place the rest at the bottom of your deck in any order.",
    image_url: "/placeholder.svg?height=838&width=600",
    alternate_art: false,
    series_id: "569302",
    series_name: "BOOSTER PACK ROMANCE DAWN [OP-01]",
    market_price: 8.99,
    sellingPrice: 9.5,
    quantity: 3,
  },
  {
    id: "OP01-047",
    name: "Sanji",
    rarity: "R",
    type: "CHARACTER",
    attribute: "Strike",
    power: 4000,
    counter: 1000,
    color: "Yellow",
    card_type: "Cook/Straw Hat Crew",
    effect:
      "[On Play] Look at 5 cards from the top of your deck and place them at the top or bottom of your deck in any order.",
    image_url: "/placeholder.svg?height=838&width=600",
    alternate_art: false,
    series_id: "569302",
    series_name: "BOOSTER PACK ROMANCE DAWN [OP-01]",
    market_price: 12.99,
    sellingPrice: 15.0,
    quantity: 1,
    multiplePrices: [15.0, 16.5],
  },
]
